### ISSUE TITLE
Swift package manager version?

### ISSUE THREAD

**Issue by SoylentGraham** [abdulkarimkhan96/LottieAnimationUsingSwiftUI#1]
Any plans to migrate away from pods to swift package manager?

**Comment by abdulkarimkhaan** [comment]
Brother @SoylentGraham, I didn't got your point. Do you mean to create my own SPM or use Lottie as SPM?

**Comment by SoylentGraham** [comment]
> Brother @SoylentGraham, I didn't got your point. Do you mean to create my own SPM or use Lottie as SPM?

Yeah. :)

Maybe a moot point now, as I'm using https://github.com/airbnb/lottie-spm as I can just install the package (I have never liked cocoapods, and swift package manager is a breath of fresh air)

**Comment by abdulkarimkhaan** [comment]
Thanks @SoylentGraham for the idea! I will definitely create SPM for this! :)
Highly Appreciated! 🙌
